#include "bst.c"

int main() {
    node *root = create_node(10);
    node *ptr = set_left(root, create_node(4));
    set_left(ptr, create_node(1));
    set_right(ptr, create_node(5));
    ptr = set_right(root, create_node(17));
    set_left(ptr, create_node(16));
    set_right(ptr, create_node(21));
    print_tree_in_order(root);
    putchar('\n');
    print_tree_iterative(root);
    putchar('\n');
    print_tree_preorder(root);
    putchar('\n');
    print_tree_postorder(root);
    putchar('\n');
    printf("%d\n", tree_search(root, 21)->key);
    printf("%p\n", (void*) tree_search(root, 22));
    printf("%d\n", iterative_tree_search(root, 17)->key);
    printf("%p\n", iterative_tree_search(root, 18));
    printf("%d\n", tree_maximum(root)->key);
    printf("%d\n", tree_minimum(root)->key);
    root = create_node(15);
    ptr = set_left(root, create_node(6));
    ptr = set_left(ptr, create_node(3));
    set_left(ptr, create_node(2));
    set_right(ptr, create_node(4));
    ptr = root->left;
    ptr = set_right(ptr, create_node(7));
    ptr = set_right(ptr, create_node(13));
    set_left(ptr, create_node(9));
    ptr = set_right(root, create_node(18));
    set_left(ptr, create_node(17));
    set_right(ptr, create_node(20));
    printf("%d\n", tree_successor(root->left->right->right)->key);
    printf("%d\n", tree_minimum_recursive(root)->key);
    printf("%d\n", tree_maximum_recursive(root)->key);
    printf("%d\n", tree_predecessor(root->left->right->right->left)->key);

    btree *tree = create_tree();
    tree_insert_key(tree, 12);
    tree_insert_key(tree, 5);
    tree_insert_key(tree, 18);
    tree_insert_key(tree, 2);
    tree_insert_key(tree, 9);
    tree_insert_key(tree, 15);
    tree_insert_key(tree, 19);
    tree_insert_key(tree, 17);
    tree_insert_key(tree, 13);
    tree_insert_key(tree, 10);
    print_tree_preorder(tree->root);
    tree_delete(tree, tree_search(tree->root, 5));
    putchar('\n');
    print_tree_preorder(tree->root);
    putchar('\n');

    tree = create_tree();
    recursive_tree_insert_key(tree, 12);
    recursive_tree_insert_key(tree, 5);
    recursive_tree_insert_key(tree, 18);
    recursive_tree_insert_key(tree, 2);
    recursive_tree_insert_key(tree, 9);
    recursive_tree_insert_key(tree, 15);
    recursive_tree_insert_key(tree, 19);
    recursive_tree_insert_key(tree, 17);
    recursive_tree_insert_key(tree, 13);
    recursive_tree_insert_key(tree, 10);
    print_tree_preorder(tree->root);
    tree_delete(tree, tree_search(tree->root, 5));
    putchar('\n');
    print_tree_preorder(tree->root);
    putchar('\n');
}